# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.4
COPY ./config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
