---
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: ${ELASTICSEARCH_URL}
monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true
## X-Pack security credentials
elasticsearch.username: "kibana_system"
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
