# Configuração da pipeline 'logges' com o identificador 'logges' e o arquivo de configuração em "/usr/share/logstash/pipeline/logges.conf".
- pipeline.id: logges
  path.config: "/usr/share/logstash/pipeline/logges.conf"

# Configuração da pipeline 'client_opcua' com o identificador 'client_opcua' e o arquivo de configuração em "/usr/share/logstash/pipeline/client_opcua.conf".
- pipeline.id: client_opcua
  path.config: "/usr/share/logstash/pipeline/client_opcua.conf"

# Configuração da pipeline 'mysql_database' com o identificador 'mysql_database' e o arquivo de configuração em "/usr/share/logstash/pipeline/mysql_database.conf".
- pipeline.id: mysql_database
  path.config: "/usr/share/logstash/pipeline/mysql_database.conf"

# Configuração da pipeline 'dead-letter-queue' com o identificador 'dead-letter-queue' e o arquivo de configuração em "/usr/share/logstash/pipeline/dlq.conf".
- pipeline.id: dead-letter-queue
  path.config: "/usr/share/logstash/pipeline/dlq.conf"
